services:
  - type: web
    name: portal-mg
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
